import { commonTexts, isLocale, type Locale } from "../i18n/index.js";

/** Example texts for the stories in both languages (zone texts live in the zones). */
const demo = {
  de: {
    accountTitle: "Mein Konto",
    lead: "Hier sehen Sie Ihre Stammdaten und Verträge.",
    heroTitle: "Strom, Gas, Wasser, Internet und Mobilfunk — alles in einem Konto",
    heroLead:
      "Dieses Kundenportal ist ein Demo-Projekt. Es zeigt, wie ein Versorger sein Portal modernisiert.",
    toAccount: "Zu Ihrem Konto",
    register: "Konto anlegen oder anmelden",
    save: "Speichern",
    cancel: "Abbrechen",
    address: "Anschrift",
    addressText: "Musterweg 1, 12345 Musterstadt",
    customerId: "Kundennummer",
    name: "Name",
    email: "E-Mail",
    since: "Kunde seit",
    sinceValue: "12. März 2019",
    readings: "Zählerstände Strom",
    date: "Datum",
    meter: "Zähler",
    reading: "Stand",
    source: "Quelle",
    sources: { customer: "Kundin", estimate: "Schätzung" },
    noReadings: "Noch keine Zählerstände",
    noReadingsText: "Tragen Sie Ihren ersten Zählerstand ein.",
    addReading: "Zählerstand erfassen",
    emailHint: "Wir schreiben Ihnen nur zu Ihrem Konto.",
    emailError: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    division: "Sparte",
    choose: "Bitte wählen",
    divisions: { power: "Strom", gas: "Gas", water: "Wasser" },
    readingHint: "Nur ganze Zahlen, ohne Nachkommastellen.",
    info: "Die Willkommensnachricht erscheint wenige Sekunden nach der ersten Anmeldung.",
    success: "Ihr Zählerstand wurde gespeichert.",
    warning: "Ihr Abschlag ist höher als der Verbrauch der letzten Monate.",
    error:
      "Ihr Konto konnte gerade nicht geladen werden. Bitte versuchen Sie es gleich noch einmal.",
    errorTitle: "Fehler",
    unread: "neu",
    saved: "gespeichert",
    migrated: "übernommen",
    conflict: "Klärfall",
    bell: "Glocke (3)",
    quotaApi: "API-Aufrufe",
    quotaApiValue: "3.800 von 5.000 übrig",
    quotaEvents: "Domänen-Ereignisse",
    quotaEventsValue: "150 von 1.000 übrig",
    quotaUploads: "Uploads",
    quotaUploadsValue: "0 von 20 übrig",
  },
  en: {
    accountTitle: "My account",
    lead: "Your master data and contracts at a glance.",
    heroTitle: "Electricity, gas, water, internet and mobile — all in one account",
    heroLead:
      "This customer portal is a demo project. It shows how a utility modernises its portal.",
    toAccount: "Go to your account",
    register: "Create an account or sign in",
    save: "Save",
    cancel: "Cancel",
    address: "Address",
    addressText: "Musterweg 1, 12345 Musterstadt",
    customerId: "Customer number",
    name: "Name",
    email: "E-mail",
    since: "Customer since",
    sinceValue: "12 March 2019",
    readings: "Electricity meter readings",
    date: "Date",
    meter: "Meter",
    reading: "Reading",
    source: "Source",
    sources: { customer: "Customer", estimate: "Estimate" },
    noReadings: "No meter readings yet",
    noReadingsText: "Enter your first meter reading.",
    addReading: "Enter a reading",
    emailHint: "We only write to you about your account.",
    emailError: "Please enter a valid e-mail address.",
    division: "Division",
    choose: "Please choose",
    divisions: { power: "Electricity", gas: "Gas", water: "Water" },
    readingHint: "Whole numbers only.",
    info: "The welcome message appears a few seconds after your first sign-in.",
    success: "Your meter reading has been saved.",
    warning: "Your instalment is higher than your consumption in recent months.",
    error: "Your account could not be loaded right now. Please try again in a moment.",
    errorTitle: "Error",
    unread: "new",
    saved: "saved",
    migrated: "migrated",
    conflict: "needs review",
    bell: "Bell (3)",
    quotaApi: "API calls",
    quotaApiValue: "3,800 of 5,000 left",
    quotaEvents: "Domain events",
    quotaEventsValue: "150 of 1,000 left",
    quotaUploads: "Uploads",
    quotaUploadsValue: "0 of 20 left",
  },
} as const;

export function storyTexts(globals: Record<string, unknown>) {
  const locale: Locale = isLocale(globals["locale"]) ? globals["locale"] : "de";
  return { locale, common: commonTexts[locale], demo: demo[locale] };
}
